pod 'RestKit', '~> 0.20.0'
pod 'MagicalRecord', '~> 2.1'
pod 'UIKitCategoryAdditions', '~> 0.0.1'
pod 'UITableView-NXEmptyView', '~> 0.1.4'
pod 'MTStatusBarOverlay', '~> 0.9.1'
pod 'SDWebImage', '~> 3.4'
pod 'Block-KVO'